steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/silken-gadget-247900/letters-app', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/silken-gadget-247900/letters-app']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'letters-app', '--image', 'gcr.io/silken-gadget-247900/letters-app', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/silken-gadget-247900/letters-app
